PrototypeSAD/Models/Stocks.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PrototypeSAD.Models
{
    public class Stocks
    {
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    }
}

PrototypeSAD/Controllers/StocksController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrototypeSAD.Controllers
{
    public class StocksController : Controller
    {
        // GET: StocksController
        public ActionResult Index()
        {
            return View();
        }

        // GET: StocksController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StocksController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StocksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                TempData["Create"] = true;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StocksController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StocksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                TempData["Edit"] = true;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StocksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StocksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PrototypeSAD/Views/Stocks/Create.cshtml
@model PrototypeSAD.Models.Stocks

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="col-12">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Price" class="control-label"></label>
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Quantity" class="control-label"></label>
                            <input asp-for="Quantity" class="form-control" />
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Picture</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input"
                                           id="exampleInputFile">
                                    <label class="custom-file-label"
                                           for="exampleInputFile">Choose Picture</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrototypeSAD/Views/Stocks/Details.cshtml
@model PrototypeSAD.Models.Stocks

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <h3 class="d-inline-block d-sm-none">
                            Ergonomics Chair
                        </h3>
                        <div class="col-12">
                            <img src="~/images/prod-1.jpg" class="product-image" alt="Product Image">
                        </div>
                        @*<div class="col-12 product-image-thumbs">
                            <div class="product-image-thumb active">
                                <img src="~/images/prod-1.jpg"
                                     alt="Product Image">
                            </div>
                            <div class="product-image-thumb">
                                <img src="~/images/prod-2.jpg"
                                     alt="Product Image">
                            </div>
                            <div class="product-image-thumb">
                                <img src="~/images/prod-3.jpg"
                                     alt="Product Image">
                            </div>
                            <div class="product-image-thumb">
                                <img src="~/images/prod-4.jpg"
                                     alt="Product Image">
                            </div>
                            <div class="product-image-thumb">
                                <img src="~/images/prod-5.jpg"
                                     alt="Product Image">
                            </div>
                        </div>*@
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">Ergonomics Chair</h3>
                        <p>
                            Ergonomic chair with 5 rolls
                        </p>

                        <hr>

                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0">
                                RM 10.70
                            </h2>
                        </div>

                        <div class="mt-4">
                            <a href="@Url.Action("Edit")" class="btn btn-primary btn-lg btn-flat">
                                <i class="fas fa-pen fa-lg mr-2"></i>
                                Edit Stock
                            </a>

                            <div class="btn btn-danger btn-lg btn-flat">
                                <i class="fas fa-trash fa-lg mr-2"></i>
                                Delete Stock
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.card-body -->

PrototypeSAD/Views/Stocks/Edit.cshtml
@model PrototypeSAD.Models.Stocks

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="col-12">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" value="Ergonomics Chair" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" value="Ergonomic chair with 5 rolls" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Price" class="control-label"></label>
                            <input asp-for="Price" class="form-control" value="10.70" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Quantity" class="control-label"></label>
                            <input asp-for="Quantity" class="form-control" value="21" />
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Picture</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input"
                                           id="exampleInputFile">
                                    <label class="custom-file-label"
                                           for="exampleInputFile">Choose Picture</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @*<a href="@Url.Action("Details")" class="btn btn-primary"><i class="fas fa-save"></i>&nbsp;Save</a>*@
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrototypeSAD/Views/Stocks/Index.cshtml
@model IEnumerable<PrototypeSAD.Models.StocksIndex>

@{
    ViewData["Title"] = "Products";
}
@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="card-title">Furniture Product</h3>
                    </div>
                    <div class="col-md-6">
                        @Html.ActionLink("New Product", "Create", "Stocks", "", new { @class = "float-right btn btn-primary" })
                    </div>
                </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Quantity)
                            </th>
                            <th class="no-sort">

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                455-981-221
                            </td>
                            <td>
                                Office Table
                            </td>
                            <td>
                                15
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details")">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="@Url.Action("Edit")">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal" data-stock="Office Table">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                247-925-726
                            </td>
                            <td>
                                Small Cabinet
                            </td>
                            <td>
                                16
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details")">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="@Url.Action("Edit")">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal" data-stock="Small Cabinet">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                735-845-642
                            </td>
                            <td>
                                Ergonomics Chair
                            </td>
                            <td>
                                21
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details")">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="@Url.Action("Edit")">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal" data-stock="Ergonomics Chair">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                422-568-642
                            </td>
                            <td>
                                Cupboard
                            </td>
                            <td>
                                44
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details")">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="@Url.Action("Edit")">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal" data-stock="Cupboard">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Warning!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span>Are you sure you want to delete D/O05-001?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" id="ok-btn" class="btn btn-danger" onclick="SuccessAlert();" data-dismiss="modal">Yes</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- DataTables  & Plugins -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/lib/jszip/jszip.min.js"></script>
    <script src="~/lib/pdfmake/pdfmake.min.js"></script>
    <script src="~/lib/pdfmake/vfs_fonts.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script>
        $(function () {
            $("table").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "columnDefs": [
                    {
                        "targets": 3,
                        "className": 'noVis'
                    }
                ],
                "buttons": ["print"],
            }).buttons().container().appendTo('#DataTables_Table_0_wrapper .col-md-6:eq(0)');

            $('#DeleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var name = button.data('stock') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title').text('Warning!')
                modal.find('.modal-body span').text("Are you sure want to delete " + name + "?")
            })

            @{
                if (TempData["Edit"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Product updated successfully.'
                    @:})
                }

                if (TempData["Create"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Product created successfully.'
                    @:})
                }
            }
        })

        var Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
        });

        function SuccessAlert() {
            Toast.fire({
                icon: 'success',
                title: 'Product deleted successfully.'
            })
        }
    </script>
}