PrototypeSAD/Controllers/DeliveryOrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrototypeSAD.Controllers
{
    public class DeliveryOrderController : Controller
    {
        // GET: DeliveryOrderController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DeliveryOrderController/Details/5
        public ActionResult Details(int id)
        {
            if(id == 1)
            {
                TempData["Create"] = true;

            }
            if(id == 2)
            {
                TempData["Edit"] = true;

            }
            return View();
        }

        // GET: DeliveryOrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DeliveryOrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DeliveryOrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DeliveryOrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DeliveryOrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DeliveryOrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PrototypeSAD/Views/DeliveryOrder/Create.cshtml
@{
    ViewData["Title"] = "New Delivery Oder";
}

<div class="row">
    <div class="col-12">
        <!-- Main content -->
        <div class="invoice p-3 mb-3">
            <!-- title row -->
            <div class="row">
                <div class="col-12">
                    <h4>
                        <i class="fas fa-globe"></i> Lean Aik Furniture
                    </h4>
                </div>
                <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col border-right">
                    From <a href="#" data-toggle="modal" data-target="#modal-edit-personal" class="float-right">Edit Details</a>
                    <address>
                        <strong>Lean Aik Furniture</strong><br>
                        4995<br />
                        Jalan New Ferry<br />
                        12100 Butterworth<br />
                        Penang<br />
                        Phone: (60) 12-454 3360<br>
                        Email: info@leanaikfurniture.com
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col border-right">
                    To <a href="#" data-toggle="modal" data-target="#modal-edit-client" class="float-right">Add Client</a>
                    <!--<address>
                            <strong>John Doe</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            Phone: (555) 539-1037<br>
                            Email: john.doe@example.com
                        </address>-->
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>Delivery Order #05-002</b><a href="#" data-toggle="modal" data-target="#modal-edit-detail" class="float-right">Edit Details</a><br>
                    <br>
                    <b>Purchase Order:</b> <br>
                    <b>Date:</b> <br>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
            <br />
            <!-- Table row -->
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Serial #</th>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Qty</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>455-981-221</td>
                                <td>Office Table</td>
                                <td>3"x4" Table</td>
                                <td><input class="form-control w-25" style="text-align: center;" value="1" /></td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <!-- <tr>
                                <td>1</td>
                                <td>Need for Speed IV</td>
                                <td>247-925-726</td>
                                <td>Wes Anderson umami biodiesel</td>
                                <td>RM 50.00</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Monsters DVD</td>
                                <td>735-845-642</td>
                                <td>Terry Richardson helvetica tousled street art master</td>
                                <td>RM 10.70</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Grown Ups Blue Ray</td>
                                <td>422-568-642</td>
                                <td>Tousled lomo letterpress</td>
                                <td>RM 25.99</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>-->
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <p><button type="button" class="btn btn-light"><i class="fas fa fa-plus-circle"></i> Add Product</button></p>

            <!-- this row will not appear when printing -->
            <div class="row no-print">
                <div class="col-12">
                    <a href="@Url.Action("Details", new { id= 1 })" class="btn btn-success float-right"><i class="far fa-save"></i> Save D/O</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.invoice -->

<div class="modal fade" id="modal-edit-personal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Information</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label for="personal-name" class="col-sm-2 col-form-label">Name : </label>
                        <div class="col-sm-10"><input id="personal-name" class="form-control" value="Lean Aik Furniture" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-address1" class="col-sm-2 col-form-label">Address : </label>
                        <div class="col-sm-10"><input id="personal-address1" class="form-control" value="4995" /></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10 offset-sm-2"><input id="personal-address2" class="form-control" value="Jalan New Ferry" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-postcode" class="col-sm-2 col-form-label">Postcode : </label>
                        <div class="col-sm-10"><input id="personal-postcode" class="form-control" value="12100" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-city" class="col-sm-2 col-form-label">City : </label>
                        <div class="col-sm-10"><input id="personal-city" class="form-control" value="Butterworth" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-state" class="col-sm-2 col-form-label">State : </label>
                        <div class="col-sm-10"><input id="personal-state" class="form-control" value="Penang" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-phone" class="col-sm-2 col-form-label">Phone No : </label>
                        <div class="col-sm-10"><input id="personal-phone" class="form-control" value="0124543360" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="personal-email" class="col-sm-2 col-form-label">Email : </label>
                        <div class="col-sm-10"><input id="personal-email" class="form-control" value="info@leanaikfurniture.com" /></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="modal-edit-client">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Client</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label for="client-name" class="col-sm-2 col-form-label">Name : </label>
                        <div class="col-sm-10"><input id="client-name" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-address1" class="col-sm-2 col-form-label">Address : </label>
                        <div class="col-sm-10"><input id="client-address1" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10 offset-sm-2"><input id="client-address2" class="form-control" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-postcode" class="col-sm-2 col-form-label">Postcode : </label>
                        <div class="col-sm-10"><input id="client-postcode" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-city" class="col-sm-2 col-form-label">City : </label>
                        <div class="col-sm-10"><input id="client-city" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-state" class="col-sm-2 col-form-label">State : </label>
                        <div class="col-sm-10"><input id="client-state" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-phone" class="col-sm-2 col-form-label">Phone No : </label>
                        <div class="col-sm-10"><input id="client-phone" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                    <div class="form-group row">
                        <label for="client-email" class="col-sm-2 col-form-label">Email : </label>
                        <div class="col-sm-10"><input id="client-email" class="form-control" data-val="true" data-val-required="This field is required." /></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="modal-edit-detail">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Details</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label for="date" class="col-sm-3 col-form-label">Purchase Order : </label>
                        <div class="col-sm-9"><input id="purchase" class="form-control" value="" placeholder="2201-001" /></div>
                    </div>
                    <div class="form-group row">
                        <label for="date" class="col-sm-3 col-form-label">Date : </label>
                        <div class="col-sm-9"><input id="date" class="form-control" placeholder="01/01/2021" /></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        $("#date").datepicker({ dateFormat: 'dd/mm/yy' });

        $('form').valida
    </script>
}

PrototypeSAD/Views/DeliveryOrder/Details.cshtml
@{
    ViewData["Title"] = "Details";
}


<div class="row">
    <div class="col-12">
        <!-- Main content -->
        <div class="invoice p-3 mb-3">
            <!-- title row -->
            <div class="row d-print-none">
                <div class="col-12">
                    <h4>
                        <i class="fas fa-globe"></i> Lean Aik Furniture
                    </h4>
                </div>
                <!-- /.col -->
            </div>
            <div class="row justify-content-center d-none d-print-block">
                <div class="col-auto">
                    <h4 class="text-center"><b>LEAN AIK FURNITURE</b></h4>
                    <h6 class="text-center">4995,TINGKAT BAWAH, JALAN NEW FERRY</h6>
                    <h6 class="text-center">12100 BUTTERWORTH, P. PINANG</h6>
                    <h6 class="text-center">Tel: (60) 12-454 3360, Fax: 04-1234567</h6>
                    <h6 class="text-center">Email:  info@leanaikfurniture.com</h6>
                </div>
            </div>
            <!-- info row -->
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col border-right">
                    From
                    <address>
                        <strong>Lean Aik Furniture</strong><br>
                        4995<br />
                        Jalan New Ferry<br />
                        12100 Butterworth<br />
                        Penang<br />
                        Phone: (60) 12-454 3360<br>
                        Email: info@leanaikfurniture.com
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col border-right">
                    To
                    <address>
                        <strong>Micron Memory Malaysia Sdn. Bhd</strong><br>
                        1063, Tingkat Perusahaan 6<br>
                        Kawasan Perusahaan Bebas Perai<br>
                        13600 Perai<br>
                        Pulau Pinang<br>
                        Phone: (60) 4-377 0500<br>
                        Email: purchase@micron.com
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>Delivery Order #05-001</b><br>
                    <br>
                    <b>Purchase Order:</b> 2201-001<br>
                    <b>Date:</b> 30/06/2021<br>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
            <br />
            <!-- Table row -->
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Serial #</th>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Qty</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>455-981-221</td>
                                <td>Office Table</td>
                                <td>3"x4" Table</td>
                                <td>1</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>247-925-726</td>
                                <td>Small Cabinet</td>
                                <td>3-layer cabinet</td>
                                <td>1</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>735-845-642</td>
                                <td>Ergonomics Chair</td>
                                <td>Ergonomic chair with 5 rolls</td>
                                <td>1</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>422-568-642</td>
                                <td>Cupboard</td>
                                <td>3x3 cupborad</td>
                                <td>1</td>
                                <td><a href="#" class="text-danger"><i class="fas fa fa-trash-alt"></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
            <br />
            <br />
            <!-- this row will not appear when printing -->
            <div class="row no-print">
                <div class="col-12">
                    <button type="button" class="btn btn-default" onclick="printPage()"><i class="fas fa-print"></i> Print</button>
                    <a href="@Url.Action("Edit")" class="btn btn-warning"><i class="far fa-edit"></i> Edit D/O</a>
                    <button data-toggle="modal" data-target="#CompleteModal" class="btn btn-success float-right">
                        <i class="far fa-credit-card"></i> Complete Delivery
                    </button>
                    <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                        <i class="fas fa-download"></i> Generate PDF
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.invoice -->

<div class="modal fade" id="CompleteModal" tabindex="-1" role="dialog" aria-labelledby="CompleteModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Warning!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span>Are you sure the delivery is completed?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" id="ok-btn" class="btn btn-danger" onclick="SuccessAlert();" data-dismiss="modal">Yes</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {

            @{
                if (TempData["Edit"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Delivery Order updated successfully.'
                    @:})
                }

                if (TempData["Create"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Delivery Order created successfully.'
                    @:})
                }
            }
        })

        var Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
        });

        function SuccessAlert() {
            Toast.fire({
                icon: 'success',
                title: 'Delivery Order status updated successfully.'
            })
        }
    </script>
}

PrototypeSAD/Views/DeliveryOrder/Index.cshtml
@{
    ViewData["Title"] = "Delivery Order";
}
@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6 offset-md-6">
                        @Html.ActionLink("New Delivery Order", "Create", "DeliveryOrder", null, new { @class = "float-right btn btn-primary" })
                    </div>
                </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                D/O. No.
                            </th>
                            <th>
                                Customer Name
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Status
                            </th>
                            <th class="no-sort"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                D/O05-001
                            </td>
                            <td>
                                Micron Memory Malaysia Sdn. Bhd
                            </td>
                            <td>
                                2021-06-30
                            </td>
                            <td>
                                <span class="badge badge-warning">Delivering</span>
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details")">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="@Url.Action("Edit")">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal">
                                    <i class="fas fa-trash">
                                    </i>
                                    Cancel
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Warning!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span>Are you sure you want to cancel D/O05-001?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" id="ok-btn" class="btn btn-danger" onclick="SuccessAlert();" data-dismiss="modal">Yes</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- DataTables  & Plugins -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/lib/jszip/jszip.min.js"></script>
    <script src="~/lib/pdfmake/pdfmake.min.js"></script>
    <script src="~/lib/pdfmake/vfs_fonts.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script>
        $(function () {
            $("table").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "columnDefs": [
                    {
                        "targets": 4,
                        "className": 'noVis',
                        "orderable": 'false'
                    }
                ],
            }).buttons().container().appendTo('#DataTables_Table_0_wrapper .col-md-6:eq(0)');

            @{
                if (TempData["Edit"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Delivery Order updated successfully.'
                    @:})
                }

                if (TempData["Create"] != null)
                {
                    @:Toast.fire({
                        @:icon: 'success',
                        @:title: 'Delivery Order created successfully.'
                    @:})
                }
            }
        })

        var Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
        });

        function SuccessAlert() {
            Toast.fire({
                icon: 'success',
                title: 'Delivery Order canceled successfully.'
            })
        }
    </script>
}